// Valid Input Fields
export const VALID_INITIATE = 'VALID_INITIATE';
export const VALID_SUCCESS = 'VALID_SUCCESS';
export const VALID_FAIL = 'VALID_FAIL';
export const IS_SHOW_POPUP = 'IS_SHOW_POPUP'

//Validate School Step One Registration
export const VALID_INITIATE_SCHOOL_STEPONE = 'VALID_INITIATE_SCHOOL_STEPONE';
export const VALID_SUCCESS_SCHOOL_STEPONE = 'VALID_SUCCESS_SCHOOL_STEPONE';
export const VALID_FAIL_SCHOOL_STEPONE = 'VALID_FAIL_SCHOOL_STEPONE';
export const IS_SHOW_POPUP_SCHOOL = 'IS_SHOW_POPUP_SCHOOL'
